export const CDN_URL = "http://ddragon.leagueoflegends.com/cdn"
export const API_URL = "https://ddragon.leagueoflegends.com/api/"
export const REALMS_URL = "http://ddragon.leagueoflegends.com/realms"
export const LANGUAGES_URL = "http://ddragon.leagueoflegends.com/cdn/languages.json"
export const VERSIONS_URL = "http://ddragon.leagueoflegends.com/api/versions.json"